services:
  manga-bot:
    build: .
    container_name: manga-discord-bot
    restart: always
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.setup:/app/.setup
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 512M
